

// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Proto/weather.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace TrpcSharp.ServerSample.Proto {
  public static partial class WeatherForecasts
  {
    static readonly string __ServiceName = "Weather.WeatherForecasts";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Empty.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::TrpcSharp.ServerSample.Proto.GetWeatherForecastsResponse> __Marshaller_Weather_GetWeatherForecastsResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::TrpcSharp.ServerSample.Proto.GetWeatherForecastsResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::TrpcSharp.ServerSample.Proto.GetWeatherForecastsResponse> __Method_GetWeatherForecasts = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::TrpcSharp.ServerSample.Proto.GetWeatherForecastsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetWeatherForecasts",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_Weather_GetWeatherForecastsResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::TrpcSharp.ServerSample.Proto.WeatherReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of WeatherForecasts</summary>
    [grpc::BindServiceMethod(typeof(WeatherForecasts), "BindService")]
    public abstract partial class WeatherForecastsBase
    {
      public virtual global::System.Threading.Tasks.Task<global::TrpcSharp.ServerSample.Proto.GetWeatherForecastsResponse> GetWeatherForecasts(global::Google.Protobuf.WellKnownTypes.Empty request, TrpcSharp.Server.UnaryTrpcContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for WeatherForecasts</summary>
    public partial class WeatherForecastsClient : grpc::ClientBase<WeatherForecastsClient>
    {
      /// <summary>Creates a new client for WeatherForecasts</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public WeatherForecastsClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for WeatherForecasts that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public WeatherForecastsClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected WeatherForecastsClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected WeatherForecastsClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::TrpcSharp.ServerSample.Proto.GetWeatherForecastsResponse GetWeatherForecasts(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetWeatherForecasts(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::TrpcSharp.ServerSample.Proto.GetWeatherForecastsResponse GetWeatherForecasts(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetWeatherForecasts, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::TrpcSharp.ServerSample.Proto.GetWeatherForecastsResponse> GetWeatherForecastsAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetWeatherForecastsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::TrpcSharp.ServerSample.Proto.GetWeatherForecastsResponse> GetWeatherForecastsAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetWeatherForecasts, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override WeatherForecastsClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new WeatherForecastsClient(configuration);
      }
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindTrpcService(TrpcSharp.Server.TrpcServices.TrpcServiceBinderBase serviceBinder, WeatherForecastsBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetWeatherForecasts, serviceImpl == null ? null : new TrpcSharp.Server.TrpcServices.TrpcUnaryMethod<global::Google.Protobuf.WellKnownTypes.Empty, global::TrpcSharp.ServerSample.Proto.GetWeatherForecastsResponse>(serviceImpl.GetWeatherForecasts));
    }

  }
}
#endregion
